version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: rec_mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: recommendation_db
    volumes:
      - mongo_data:/data/db
    networks:
      - rec_network

  redis:
    image: redis:7.0
    container_name: rec_redis
    ports:
      - '6379:6379'
    networks:
      - rec_network

networks:
  rec_network:
    driver: bridge

volumes:
  mongo_data:
